### ISSUE TITLE
Unable to reach from outside the computer it runs on

### ISSUE THREAD

**Issue by Br3akout** [DarkflameUniverse/AccountManager#13]
Im using WSL2 and the computer that it runs on is the only one in the network (or outside the network) who can reach the Server through the IP it provides. Everyone else gets "connection time-out"

**Comment by aronwk-aaron** [comment]
are you port forwarding 5000?
are they using your public IP?

**Comment by Br3akout** [comment]
> are you port forwarding 5000? are they using your public IP?

I guess so. The server says: Running on http://[someipadress]:5000/
They cant connect with my public IP from my windows machine and the cant connect to http://[someipadress]:5000/ either.

**Comment by aronwk-aaron** [comment]
then you don't have port forwarding setup in your router

**Comment by Br3akout** [comment]
It was set, I recently learned that it is a WSL issue that prohibits anyone from outside the home network to connect to anything on the WSL distribution. I switched to an VPS and now everything works.

**Comment by bingo5387** [comment]
Another possible solution for this is using LogMeIn Hamachi. LogMeIn Hamachi provides you with an IP address which you can manually set app.py to use (replace 0.0.0.0 near the bottom). The downside is that anyone else accessing the site needs to download it as well and join a network you create, which is limited to 5 people, including yourself (on the free version). Also not sure if this works in WSL2 or not, I did it in WSL1. I'm trying to get this working for the actual server as well, but I haven't had luck so far.
