### ISSUE TITLE
Backend permits empty username and password

### ISSUE THREAD

**Issue by Marcono1234** [DarkflameUniverse/AccountManager#16]
It looks like the backend permits an empty username and password (given a valid play key) on http://localhost:5000/activate.
This should probably be prevented.

![Account creation success screenshot](https://user-images.githubusercontent.com/11685886/147699538-7a927f4b-3902-47af-b080-0c5cd7fbdb4a.png)

Maybe [Flask-WTF](https://flask-wtf.readthedocs.io/en/1.0.x/) could be used for all backend input validation.

**Comment by aronwk-aaron** [comment]
fixed
