### ISSUE TITLE
Only show Privacy Policy and Terms of Service checkbox when these files exist

### ISSUE THREAD

**Issue by Marcono1234** [DarkflameUniverse/AccountManager#17]
It looks like the account creation page on  http://localhost:5000/activate always shows a "I agree to the Privacy Policy and Terms of Service" checkbox even though the linked files do not exist:

![Checkbox screenshot](https://user-images.githubusercontent.com/11685886/147699761-0e813560-2387-488e-8ba7-582f7dac42c8.png)

Would it be possible to only show this checkbox conditionally, when the files exist, or to remove it completely? Or is the Darkflame server collecting telemetry data (or similar) by default?

**Comment by aronwk-aaron** [comment]
See comment on PR #21
