### ISSUE TITLE
Use "Post/Redirect/Get" pattern to prevent accidentally resubmitting form

### ISSUE THREAD

**Issue by Marcono1234** [DarkflameUniverse/AccountManager#19]
Would it be possible to use the ["Post/Redirect/Get" pattern](https://en.wikipedia.org/wiki/Post/Redirect/Get) to prevent accidentally resubmitting a form?

For example currently when you generate a play key on the dashboard and try to reload the page, the browser asks you if you want to resubmit the data (that is, again generating a key). This is rather irritating.

Based on [this StackOverflow answer](https://stackoverflow.com/a/41535663) it sounds like this is possible to implement with Flask.

**Comment by aronwk-aaron** [comment]
Non-issue, works as intended
