### ISSUE TITLE
Allow for management of custom names

### ISSUE THREAD

**Issue by Lego6245** [DarkflameUniverse/AccountManager#2]
From what I understand, the only way to "approve" a custom name involves editing the DB row for that character to overwrite the pending_name into the name field. It would be convenient for admin users to be able to do this from the AccountManager instead of going into the DB directly.

**Comment by EliteMasterEric** [comment]
Agreed. Reportedly the DLU closed alpha had a method of doing this but it was forgotten about during the source release.

The AccountManager is the best place for stuff like this to be managed.

**Comment by aronwk-aaron** [comment]
See Nexus Dashboard for this functionality and more
