### ISSUE TITLE
Account Manager issue

### ISSUE THREAD

**Issue by Lego458** [DarkflameUniverse/AccountManager#24]
Hello All,
I have been using Elocore's guide on Youtube and have got to the part where I run the application, however when I use 'python3 app.py' and copy & paste it into google it comes up a 'refused to connect' error. I don't know whether it is a mistake that I've made whilst following the steps or whether its something that I need to amend on my desktop.

P.S Sorry if I haven't explained this in enough detail, I'm new to this.

Thanks in advance.

**Comment by TakumiKai25** [comment]
Did you make sure it had been connected to your database and mysql was running?

**Comment by aronwk-aaron** [comment]
Try using nexus dashboard and following it's guide
