### ISSUE TITLE
Allow ban/unban and mute/unmute of users from AccountManager

### ISSUE THREAD

**Issue by EliteMasterEric** [DarkflameUniverse/AccountManager#3]
Currently you need to enter the game or edit the database to mute or ban a user, and you can currently only unban users by entering the database.

Having these functions accessible via a web interface would be convenient for server managers.

**Comment by aronwk-aaron** [comment]
Added in #10 WIP: Overhaul

**Comment by EliteMasterEric** [comment]
> Added in #10 WIP: Overhaul

Can't wait!

**Comment by aronwk-aaron** [comment]
Move to nexus dashboard
