### ISSUE TITLE
Running, but doesn't seem to do anything.

### ISSUE THREAD

**Issue by Tyrobag** [DarkflameUniverse/AccountManager#4]
I'm sure its just something I don't know, but when I run app.py all that happens is I get this:
`user@PowerEdge-T610:~/Desktop/LU TEMP/AccountManager-main$ python3 app.py
 * Serving Flask app 'app' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://10.0.0.223:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 130-570-231
`

Then nothing happens. I can use ctrl+c to quit, but there doesn't seem to be anything else that I can do. I'm using Ubuntu.

**Comment by dddddddd207** [comment]
Visit `http://10.0.0.223:5000/` in your browser to see the interface. You can then go to `http://10.0.0.223:5000/activate` to create users, and `http://10.0.0.223:5000/login` to generate CD keys and see user statistics
