### ISSUE TITLE
Cant reach database

### ISSUE THREAD

**Issue by Alectmc** [DarkflameUniverse/AccountManager#7]
Error being thrown when trying to login to the account manager: sqlalchemy.exc.OperationalError
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '<localhost>' ([Errno -2] Name or service not known)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)

Any ideas on how to fix?

**Comment by CodingWithEjay** [comment]
Hi @Alectmc, did you figure out a solution to this? I'm having the same issue as well.
